# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Sebastian Goscik
tagline:             Maker, Hacker and Electronic Engineer
url:                 http://goscik.com
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-gist

permalink: /:categories/:title/

include: .nojekyll
